### ISSUE TITLE
No WDIData.csv dataset

### ISSUE THREAD

**Issue by greglecki** [PacktPublishing/Practical-Time-Series-Analysis#2]
Hi, I'm going through chapter one and it says that I can find the data files in this repo but there is no one called WDIData.csv. Even in Chapter_1_Different_Types_of_Data.ipynb notebook there is a reference to this csv but the files doesn't exists here.

**Comment by lclemente** [comment]
Yes, please at least keep consistency between the book and repo, folders have also different names.

**Comment by ajcanepa** [comment]
It's seems no results on this issue yet. I would like to continuous using (citing) this book, but get stuck in the first chapter by the lack of data...please try to solve it!

**Comment by ajcanepa** [comment]
After trying googling the name of the database I have found the following:

Data Host:
https://datacatalog.worldbank.org/dataset/world-development-indicators

Some discussion about the data:
https://www.kaggle.com/worldbank/world-development-indicators/discussion/38893

Hopefully thi sdata can reflect what is shown on the book!
