### ISSUE TITLE
Chapter1: Monthly_CO2_Concentrations.xlsx dataset corrupted

### ISSUE THREAD

**Issue by ajitminj** [PacktPublishing/Practical-Time-Series-Analysis#7]
Hi, unable to read the Monthly_CO2_Concentrations.xlsx dataset as the data is corrupted.

screenshot attached for reference
![dataset snapshot](https://user-images.githubusercontent.com/78618736/183127357-5538dfd4-ea37-425e-a320-19b0bdb01ac5.PNG)
.

Kindly upload the clean dataset for practice.
Thank You!

**Comment by ajitminj** [comment]
Tried to open in Ms-excel also, error message says file is corrupted.

**Comment by shubham763** [comment]
Hi @ajitminj 

Thank you for informing me, I downloaded the file and was able to open it in MS Excel. I've attached the file -

[Monthly_CO2_Concentrations.xlsx](https://github.com/PacktPublishing/Practical-Time-Series-Analysis/files/9413044/Monthly_CO2_Concentrations.xlsx)

Please let me know if the issue persists.

Regards,
Shubham

**Comment by ajitminj** [comment]
Thanks alot!
